import * as React from 'react';
import Head from 'next/head'


interface IPageHeadProps {
    titleText?: string,
    children?: React.ReactNode
}


export default function PageHead(props: IPageHeadProps) {  
    const { titleText, children } = props;

    return (
      <>
        <Head>
            <title>{titleText}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <link
                rel="stylesheet"
                href="https://fonts.googleapis.com/icon?family=Material+Icons"
            />
            {children}
        </Head>
      </>
    )
}