import React from "react";
import Head from "next/head";

interface IMetaHeadProps {
  title?: string;
  children?: React.ReactNode;
}

const MetaHead = (props: IMetaHeadProps) => {
  const { title, children } = props;

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        {children}
      </Head>
    </>
  );
};

export default MetaHead;
